### ISSUE TITLE
No namespacing of attributes attribute allowed

### ISSUE THREAD

**Issue by larsenwork** [d9d/atom-linter-jade#9]
```
svg.pencil-icon
  use(xlink:href='#icon-pencil')
```

The linter doesn't like the `xlink:href` part - can't really be written otherwise so maybe `xlink:href` should be an exception?

**Comment by zyklus** [comment]
Hi, this is a problem with the linter.  This package is only responsible for showing the output of the linter.  I suggest you open the same issue against the jade project itself.

**Comment by benedfit** [comment]
This error is coming from `jadelint` rather than `jade-lint` (now named `pug-lint`).

Given that `jadelint` is no longer maintained would you be open to the idea of the atom linter only using `pug-lint`?
